export default {
  // LOGIN
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  // TIMER
  START_TIMER: 'START_TIMER',
  STOP_TIMER: 'STOP_TIMER',
  // POMODORO
  POMODORO_START: 'POMODORO_START',
  POMODORO_STOP: 'POMODORO_STOP',
  POMODORO_START_WORK: 'POMODORO_START_WORK',
  POMODORO_START_BREAK: 'POMODORO_START_BREAK',
};
